### ISSUE TITLE
实验部分咨询

### ISSUE THREAD

**Issue by zjjhit** [jacklxc/StandAloneSpellingCorrection#1]
题主您好，在拜读您的论文，对于实验部分，您的baseline有一个选的是 MUDE，请问选这个的背景是什么（此论文2091年主要是讨论分词的，与本文的主题是否相关）？

**Comment by jacklxc** [comment]
请你再确认一下你找到的MUDE论文是否是这一篇：https://ojs.aaai.org//index.php/AAAI/article/view/6463 ？这篇文章就是研究拼写纠正的。
