### ISSUE TITLE
测试集&校验集

### ISSUE THREAD

**Issue by zhixuzhichang** [jacklxc/StandAloneSpellingCorrection#2]
非常感谢您的大作，想复现下您的实验结果，方便分享下您的测试集和校验集嘛？

**Comment by jacklxc** [comment]
原始的测试集和校验集太大了，不方便分享。你可以参照README里的Dataset Creation重构数据集，我提供了所有数据来源和代码。除非要求复现一模一样的结果，复现大致的结论应该是非常容易的，我们的方法相比baseline有很大提升。如果只是应用，长话短说就是使用你喜欢的语言模型使用论文里的方法使用NER任务训练即可，比如直接用Huggingface Transformers的BERTforTokenClassification。
