### ISSUE TITLE
BUG? 评测指标中FP,FN的计算实现和论文不符

### ISSUE THREAD

**Issue by chenkq7** [jacklxc/StandAloneSpellingCorrection#3]
代码中实现的评价指标和论文Table 3中的定义不符。

论文中的定义是：
![Screenshot_20210408_110106](https://user-images.githubusercontent.com/45423530/113962215-d18b2300-9859-11eb-9361-5cde31798a6a.png)

代码中似乎把pred和gold是搞反了？
https://github.com/jacklxc/StandAloneSpellingCorrection/blob/c4afb6aea86cd1aa02b6a2d1a482a06fdc54fc1b/MUDE/experiment.py#L215

**Comment by jacklxc** [comment]
四种情况互相独立，我先判断哪两个变量实际效果都是一样的。如果我的代码直接调换pred和gold，那还应该同时调换FP和TN，否则才是bug。

**Comment by chenkq7** [comment]
> 四种情况互相独立，我先判断哪两个变量实际效果都是一样的。如果我的代码直接调换pred和gold，那还应该同时调换FP和TN，否则才是bug。

可以先把pred和gold放一起判断。也可以先把token和gold放在一起判断。但是不能先把pred和token放在一起判断。

例子直观点儿：
| Ground Truth | Noisy Input | Prediction | 按照论文中的定义 | 按照代码中的实现 |
| ------------ | ----------- | ---------- | ---------------- | ---------------- |
| apple        | aple(X)     | ample(X)   | FN               | FP               |
| apple        | aple(X)     | aple(X)    | FN               | FN               |

代码中的计算方式会把很多FN错误地归到FP的类别中：“这个单词需要改正，但是改错了”
只有小部分FN仍然在FN类别中：“这个单词需要改正，但是没改动”

**Comment by jacklxc** [comment]
你说的有道理，谢谢你的指正。这个实现错误导致论文中的结果Recall普遍偏高，Precision偏低。不过所幸所有比较均为模型间的横向比较，直接比较Precison和Recall的情况结果悬殊非常大。所以总的结论和趋势都是不变的。
